In [ ]:
# libraries
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/Mobile Reviews Sentiment null.csv")

In [5]:
df.head(10)

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating,...,language,review_date,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,helpful_votes,source
0,1,Aryan Maharaj,45,Realme,Realme 12 Pro,337.31,₹27996.73,INR,83.00,2.0,...,Hindi,11/6/2023,True,1,1,3,2,1,1,Amazon
1,2,Davi Miguel Sousa,18,Realme,Realme 12 Pro,307.78,R$1754.35,BRL,5.70,4.0,...,Portuguese,3/30/2023,True,3,2,4,3,2,5,Flipkart
2,3,Pahal Balay,27,Google,Pixel 6,864.53,₹71755.99,INR,83.00,4.0,...,Hindi,12/7/2022,True,3,5,3,2,4,8,AliExpress
3,4,David Guzman,19,Xiaomi,Redmi Note 13,660.94,د.إ2425.65,AED,3.67,3.0,...,English,3/11/2025,False,1,3,2,1,2,3,Amazon
4,5,Yago Leão,38,Motorola,Edge 50,792.13,R$4515.14,BRL,5.70,3.0,...,Portuguese,9/29/2023,True,3,3,2,2,1,0,BestBuy
5,6,Lara Abreu,38,Apple,iPhone 14,948.79,R$5408.1,BRL,5.70,5.0,...,Portuguese,6/27/2023,False,5,4,5,5,4,6,AliExpress
6,7,Gina Moore,40,OnePlus,OnePlus 12,420.13,د.إ1541.88,AED,3.67,3.0,...,English,3/27/2024,False,3,3,2,1,2,2,eBay
7,8,James Howard,39,Apple,iPhone SE,1443.76,A$2208.95,AUD,1.53,2.0,...,English,4/8/2024,True,2,1,2,2,2,3,Amazon
8,9,Rosalia Beyer,32,Realme,Realme 12 Pro,275.73,€256.43,EUR,0.93,4.0,...,German,10/4/2024,False,4,3,2,3,3,8,eBay
9,10,Valerie Gray,31,OnePlus,OnePlus Nord 3,545.57,A$834.72,AUD,1.53,3.0,...,English,2/25/2025,True,2,2,3,3,2,4,BestBuy

In [6]:
df.columns.tolist()

['review_id',
 'customer_name',
 'age',
 'brand',
 'model',
 'price_usd',
 'price_local',
 'currency',
 'exchange_rate_to_usd',
 'rating',
 'sentiment',
 'country',
 'language',
 'review_date',
 'verified_purchase',
 'battery_life_rating',
 'camera_rating',
 'performance_rating',
 'design_rating',
 'display_rating',
 'helpful_votes',
 'source']

In [7]:
print(df["brand"].unique())
print(df["model"].unique())

<StringArray>
['Realme', 'Google', 'Xiaomi', 'Motorola', 'Apple', 'OnePlus', 'Samsung']
Length: 7, dtype: str
<StringArray>
[  'Realme 12 Pro',         'Pixel 6',   'Redmi Note 13',         'Edge 50',
       'iPhone 14',      'OnePlus 12',       'iPhone SE',  'OnePlus Nord 3',
       'Mi 13 Pro',    'Moto G Power', 'Realme Narzo 70',  'Galaxy Note 20',
        'Pixel 7a',         'Razr 40',         'Poco X6',   'iPhone 15 Pro',
         'Pixel 8',       'iPhone 13',      'Galaxy S24',      'Galaxy A55',
     'OnePlus 11R',   'Galaxy Z Flip']
Length: 22, dtype: str

In [8]:
print(df["country"].unique())
print(df["sentiment"].unique())

<StringArray>
['India', 'Brazil', 'UAE', 'Australia', 'Germany', 'UK', 'Canada', 'USA']
Length: 8, dtype: str
<StringArray>
['Negative', 'Positive', 'Neutral', nan]
Length: 4, dtype: str

In [9]:
print(df["source"].unique())
print(df["language"].unique())

<StringArray>
['Amazon', 'Flipkart', 'AliExpress', 'BestBuy', 'eBay', nan]
Length: 6, dtype: str
<StringArray>
['Hindi', 'Portuguese', 'English', 'German']
Length: 4, dtype: str

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   review_id             50000 non-null  int64
 1   customer_name         50000 non-null  str
 2   age                   50000 non-null  int64
 3   brand                 50000 non-null  str
 4   model                 50000 non-null  str
 5   price_usd             47550 non-null  float64
 6   price_local           47569 non-null  str
 7   currency              50000 non-null  str
 8   exchange_rate_to_usd  50000 non-null  float64
 9   rating                47547 non-null  float64
 10  sentiment             47555 non-null  str
 11  country               50000 non-null  str
 12  language              50000 non-null  str
 13  review_date           50000 non-null  str
 14  verified_purchase     50000 non-null  bool
 15  battery_life_rating   50000 non-null  int64
 16  camera_rating         50000 non-null  int64
 17  performance_rating    50000 non-null  int64
 18  design_rating         50000 non-null  int64
 19  display_rating        50000 non-null  int64
 20  helpful_votes         50000 non-null  int64
 21  source                47552 non-null  str
dtypes: bool(1), float64(3), int64(8), str(10)
memory usage: 8.1 MB

In [11]:
df.isnull().sum()

review_id                  0
customer_name              0
age                        0
brand                      0
model                      0
price_usd               2450
price_local             2431
currency                   0
exchange_rate_to_usd       0
rating                  2453
sentiment               2445
country                    0
language                   0
review_date                0
verified_purchase          0
battery_life_rating        0
camera_rating              0
performance_rating         0
design_rating              0
display_rating             0
helpful_votes              0
source                  2448
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,review_id,age,price_usd,exchange_rate_to_usd,rating,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,helpful_votes
count,50000.000000,50000.000000,47550.00000,50000.000000,47547.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,30.075220,689.89277,12.057946,3.123415,2.71800,2.717640,2.719620,2.713960,2.721280,3.644180
std,14433.901067,8.931307,310.32722,26.553332,1.249067,1.34827,1.345001,1.349208,1.343346,1.352121,2.432745
min,1.000000,18.000000,180.02000,0.780000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,12500.750000,23.000000,450.75500,1.000000,2.000000,1.00000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,25000.500000,29.000000,637.58500,1.530000,3.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000
75%,37500.250000,36.000000,901.45750,5.700000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,5.000000
max,50000.000000,65.000000,1499.89000,83.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,17.000000

In [14]:
(df.isnull().sum(axis=1) > 0).mean() * 100

np.float64(22.116)

In [15]:
df.isnull().sum(axis=1).value_counts().sort_index()

0    38942
1     9950
2     1050
3       55
4        3
Name: count, dtype: int64